### ISSUE TITLE
Breaking changes to ibis

### ISSUE THREAD

**Issue by emdann** [scverse/genomic-features#77]
### Report

New `ibis` release breaks the core `gene` function (see also in CI)
```python
ensdb = genomic_features.ensembl.annotation(species="Hsapiens", version="108")
genes = ensdb.genes()
```
throws
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/oak/stanford/groups/pritch/users/emma/miniforge3/envs/perturb-vs-tissue-env/lib/python3.10/site-packages/genomic_features/ensembl/ensembldb.py", line 123, in genes
    query = self.db.table("gene").filter(filter.convert())
  File "/oak/stanford/groups/pritch/users/emma/miniforge3/envs/perturb-vs-tissue-env/lib/python3.10/site-packages/ibis/expr/types/relations.py", line 2486, in filter
    raise com.IbisInputError("You must pass at least one predicate to filter")
ibis.common.exceptions.IbisInputError: You must pass at least one predicate to filter
```

Quick fix: downgrading to `ibis-framework[sqlite, duckdb]==8.0.0`

**Comment by pablo-gar** [comment]
This is caused by passing and empty filter. Fixed here #79
